USE CEU_DATABASE;
SET FOREIGN_KEY_CHECKS = 0; 

LOAD DATA INFILE 'departments.csv' INTO TABLE departments FIELDS TERMINATED BY ',' ENCLOSED BY '"'  LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA INFILE 'programs.csv' INTO TABLE programs FIELDS TERMINATED BY ',' ENCLOSED BY '"'  LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA INFILE 'instructors.csv' INTO TABLE instructors FIELDS TERMINATED BY ',' ENCLOSED BY '"'  LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA INFILE 'courses.csv' INTO TABLE courses FIELDS TERMINATED BY ',' ENCLOSED BY '"'  LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA INFILE 'students.csv' INTO TABLE students FIELDS TERMINATED BY ',' ENCLOSED BY '"'  LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA INFILE 'exams.csv' INTO TABLE exams FIELDS TERMINATED BY ',' ENCLOSED BY '"'  LINES TERMINATED BY '\n' IGNORE 1 LINES;

LOAD DATA INFILE 'students_exams.csv' INTO TABLE students_exams FIELDS TERMINATED BY ',' ENCLOSED BY '"'  LINES TERMINATED BY '\n' IGNORE 1 LINES;

SET FOREIGN_KEY_CHECKS = 1;